# Generated by Django 3.1.6 on 2021-02-05 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210205_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='valid_time',
            field=models.DurationField(choices=[(datetime.timedelta(days=28), '1 month'), (datetime.timedelta(days=168), '6 months'), (datetime.timedelta(days=336), '1 year'), (datetime.timedelta(days=672), '2 years')], default=datetime.timedelta(days=28)),
        ),
    ]
