# Generated by Django 3.1.6 on 2021-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210205_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='activation_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=-1, verbose_name='Price per month($)'),
        ),
    ]
